#ifndef APP_CONFIG_H_INCLUDED
#define APP_CONFIG_H_INCLUDED

/*
 *  Macro riguardanti la configurazione dell'applicazione
 */

#define APP_CONFIG_TASK_SIZE 512

#define APP_CONFIG_PASSWORD "42048"

#define APP_CONFIG_WIFI_SSID "HSW-OTA"
#define APP_CONFIG_WIFI_PASS "otapassword"


#define APP_CONFIG_MIN_MINIMUM_SPEED 20
#define APP_CONFIG_MAX_MINIMUM_SPEED 80
#define APP_CONFIG_MAX_SPEED         90

#define APP_CONFIG_MIN_NORMAL_BRIGHTNESS  20
#define APP_CONFIG_MAX_NORMAL_BRIGHTNESS  100
#define APP_CONFIG_MIN_STANDBY_BRIGHTNESS 0
#define APP_CONFIG_MAX_STANDBY_BRIGHTNESS APP_CONFIG_MIN_NORMAL_BRIGHTNESS


#endif
